### PR TITLE
Support assets in nested folders

### PR DESCRIPTION
**Pull request by emilbayes**
This expands all RegEx's to accept / as a valid char in the path matching group

### CODE REVIEW

**Comment by YerkoPalma** [comment]
This seems to be highly related to #396. I think both PR should be merged or something

**Comment by emilbayes** [comment]
I actually think #396 makes this PR obsolete. That PR also has tests and is more thorougher, just didn't see it before I submitted this

**Comment by YerkoPalma** [comment]
:open_mouth: you are right, didn't see that included tests have nested folders in it.

**Comment by yoshuawuyts** [comment]
Cool, yeah closing in favor of #396 then! :sparkles:

**Pull request closed without merging**
